### ISSUE TITLE
KeyError: 'kodi'

### ISSUE THREAD

**Issue by dvdbouns** [vadyur/script.module.vsdbg#2]
Hello @vadyur,

Thank you for this plugin !
Do you have any idea why i have this error ?

(I use vscode and kodi matrix on macos. I have the same error with windows)

Best regards

`ERROR <general>: E+00000.043: Error evaluating "sysconfig.get_path('stdlib')"

                                                                Traceback (most recent call last):
                                                                  File "/Users/dvdbouns/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/common/log.py", line 303, in report_paths
                                                                    paths = get_paths()
                                                                  File "/Users/dvdbouns/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/common/log.py", line 301, in <lambda>
                                                                    get_paths = lambda: util.evaluate(expr)
                                                                  File "/Users/dvdbouns/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/common/util.py", line 19, in evaluate
                                                                    return eval(expr, {}, sys.modules)
                                                                  File "/Users/dvdbouns/.vscode/extensions/ms-python.python-2021.4.765268190/pythonFiles/lib/python/debugpy/common/util.py", line 1, in <module>
                                                                    # Copyright (c) Microsoft Corporation. All rights reserved.
                                                                  File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/sysconfig.py", line 513, in get_path
                                                                    return get_paths(scheme, vars, expand)[name]
                                                                  File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/sysconfig.py", line 503, in get_paths
                                                                    return _expand_vars(scheme, vars)
                                                                  File "/Applications/Kodi.app/Contents/Libraries/lib/python3.8/sysconfig.py", line 174, in _expand_vars
                                                                    for key, value in _INSTALL_SCHEMES[scheme].items():
                                                                KeyError: 'kodi'`

**Comment by vadyur** [comment]
Hello,

VSCode mode isn't completed now. I will try fix it ASAP.

**Comment by dvdbouns** [comment]
Ok , thank you so much !

**Comment by dvdbouns** [comment]
Hello @vadyur,
Do you have any news ?
Thank
